<template>
    <h1 class="text-5xl text-center font-bold my-10">
           Committee Details
    </h1>
    <DataTable :value="names.chiefpatrons" class="mx-10 mb-10">
        <Column field="Name" header=Name></Column>
        <Column field="Role" header="Title"></Column>
    </DataTable>
</template>

<script setup>
    import { ref } from 'vue'
    import Button from "primevue/button"
    import DataTable from 'primevue/datatable';
    import Column from 'primevue/column';

    const names = {
            advisoryCommittee: [
                {Name: "Dr PARAMESHACHARI", Role: "IEEE Student Chapter Chair, Bengaluru"},
                {Name: "Dr Fr. BENNY THOMAS", Role: "Director, BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr Fr. BIJU K C", Role: "Associate Director, BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Fr. VINOD MICHAEL", Role: "Administrative Officer, BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr JOBY THOMAS", Role: "Dean, BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr RAGHUNANDAN", Role: "Associate Dean, CHRIST (Deemed to be University)"}
            ],
            chiefpatrons: [
                {Name: "Dr Fr Varghese Vithayathil", Role: "Chancellor, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr Fr Joseph C C", Role: "Vice Chancellor, CHRIST (Deemed to be University), Bangalore, India"}
            ],
            financeCommittee: [
                {Name: "Fr. VINOD MICHAEL", Role: "Administrator, BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr JAYAPRIYA J", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr KALPANA P", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr GAYATHRY S WARRIAR", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"}
            ],
            generalChairs: [
                {Name: "Dr SIVA BALAN R V", Role: "Associate Professor, Department of Computer Science BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr RAJU RAMAKRISHNA GONDKAR", Role: "Professor, Department of Computer Science BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr J. LOVELINE ZEEMA", Role: "Assistant Professor, Department of Computer Science BYC Campus, CHRIST (Deemed to be University), Bangalore, India"}
            ],
            honoraryChairs: [
                {Name: "Dr JOBY THOMAS", Role: "Dean, BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr PARAMESHACHARI", Role: "IEEE Student Chapter Chair, Bengaluru"},
                {Name: "Dr VINAY M", Role: "Computer Science Programme Coordinator, BYC Campus, CHRIST (Deemed to be University), Bangalore, India"}
            ],
            logisticsAndHospitality: [
                {Name: "Dr RAM KUMAR S", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr ASWIN I C", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr JAYADURGA", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"}
            ],
            organizingCommittee: [
                {Name: "Dr VINAY M", Role: "Programme Co-Ordinator, Department of Computer Science BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr RAJU RAMAKRISHNA GONDKAR", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr SIVA BALAN R V", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr J.LOVELINE ZEEMA", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr DEEPA S", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr BALAKRISHNAN C", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr RAMKUMAR S", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr KALPANA P", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr TEENA JOSE", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr GOBINATH R", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr JAYAPRIYA J", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr KOKILAVANI T", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr SUGANTHI", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr STEPHEN R", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr GAYATHRY S WARRIER", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr SINDHU V", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr MAHALAKSHMI J", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr JAYADURGA R", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr LAXMI BASAPPA DHARMANNAVAR", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr ASWIN I C", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"}
            ],
            patrons: [
                {Name: "Dr Fr. VIJU P D CMI", Role: "Pro-Vice Chancellor, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr Fr. BENNY THOMAS", Role: "Director, BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr Fr. JOSEPH VARGHESE KUREETHARA", Role: "CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr Fr. BIJU K C", Role: "Associate Director, BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Fr. VINOD MICHAEL", Role: "Administrative Officer, BYC Campus, CHRIST (Deemed to be University), Bangalore, India"}
            ],
            pubcom: [
                {Name: "Dr BALAKRISHNAN C", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr DEEPA S", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr SIKHAR TYAGI", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"}
            ],
            publicitycom: [
                {Name: "Dr DEEPA S", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr TEENA JOSE", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr BALAKRISHNAN C", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr MAHALAKSHMI J", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr GAYATHRY S WARRIER", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"}
            ],
            sescom: [
                {Name: "Dr LAXMI DHARMANNAVAR", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr GAYATHRY S WARRIAR", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"},
                {Name: "Dr MAHALAKSHMI J", Role: "BYC Campus, CHRIST (Deemed to be University), Bangalore, India"}
            ],
            stuBranch: [
                {Name: "AANISHA BASAK", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ADITHYA C P", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ALEENA PAUL K", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "CATHARIN NIVITHA P", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "DEVA NANDAN S", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "EVANGILIN K", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "AAN MARIA JAMES", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ADITI SINGH", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ANGELINE A", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ASHWINI S R", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "BLESSY LOUIS", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"}
            ],
            stuChapter: [
                {Name: "HARINI R", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "JANITA DEVASSY", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "JINTA MARIAM KURIAN", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "JOEL JAISON", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "KARUN BAJI", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "LAKSHMI GOPINATH", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "MADHUSNATA KAR", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "MUTHA KAVITHA", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "NANDANA KRISHNAN S", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "NEHALAL D S", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "NIDHI BENNY", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "NISHITA SHEKHAR BALA", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "PARVATHI P M", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "SIBIX JOY", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "SREE VANI BANDI", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "TESSA S MAMPILLY", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "YASHASWI D", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "PAYAL", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "HINGORANI BHUMIKA SHANKARLAL", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "JOSLYN BIJU", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "KARINA SEBASTIAN", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "KEERTHI T N", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "M POOJA", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "PRITHA CHOUDHURY", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "RIYA BANSILAL MULANI", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "SAKSHI PURSWANI", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "AKSHAT GARG", Role: "4BCA A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ARUSH DUA", Role: "4BCA A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "AKSHAT AGRAWAL", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "AMOGH SAHORE", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ANKIT KUMAR SAHOO", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "DARSHAN CHOPRA", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "GULGULIA KHUSH PRADEEP", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "KRISHNA NAND KUMAR", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "MADHAV BHATNAGAR", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "MIR HASIBUL RAHMAN", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "NISHIT AGARWAL", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "RISHI RAJ", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "RUDRAKSH GOHIL", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "RYAN NOLASCO D MELLO", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "SHORYA RAWAL", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "SOORAJ SHINE", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ANGEL BLESSY", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "SHAMBHAVI SINHA", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"}
            ],
            stuVol: [
                {Name: "AANISHA BASAK", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ADITHYA C P", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ALEENA PAUL K", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "CATHARIN NIVITHA P", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "DEVA NANDAN S", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "EVANGILIN K", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "AAN MARIA JAMES", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ADITI SINGH", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ANGELINE A", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ASHWINI S R", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "BLESSY LOUIS", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "HARINI R", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "JANITA DEVASSY", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "JINTA MARIAM KURIAN", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "JOEL JAISON", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "KARUN BAJI", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "LAKSHMI GOPINATH", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "MADHUSNATA KAR", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "MUTHA KAVITHA", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "NANDANA KRISHNAN S", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "NEHALAL D S", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "NIDHI BENNY", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "NISHITA SHEKHAR BALA", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "PARVATHI P M", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "SIBIX JOY", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "SREE VANI BANDI", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "TESSA S MAMPILLY", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "YASHASWI D", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "PAYAL", Role: "3MDS A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "HINGORANI BHUMIKA SHANKARLAL", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "JOSLYN BIJU", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "KARINA SEBASTIAN", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "KEERTHI T N", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "M POOJA", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "PRITHA CHOUDHURY", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "RIYA BANSILAL MULANI", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "SAKSHI PURSWANI", Role: "3MDS B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "AKSHAT GARG", Role: "4BCA A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ARUSH DUA", Role: "4BCA A BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "AKSHAT AGRAWAL", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "AMOGH SAHORE", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ANKIT KUMAR SAHOO", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "DARSHAN CHOPRA", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "GULGULIA KHUSH PRADEEP", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "KRISHNA NAND KUMAR", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "MADHAV BHATNAGAR", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "MIR HASIBUL RAHMAN", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "NISHIT AGARWAL", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "RISHI RAJ", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "RUDRAKSH GOHIL", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "RYAN NOLASCO D MELLO", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "SHORYA RAWAL", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "SOORAJ SHINE", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "ANGEL BLESSY", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"},
                {Name: "SHAMBHAVI SINHA", Role: "4BCA B BYC CAMPUS, CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE, INDIA"}
            ],
            techCom: [ 
                    {Name: "Dr. J.Loveline Zeema", Role: "Department of Computer Science, Christ (Deemed to be University), Bangalore Yeshwantpur campus, Nagasandra, Bengaluru, Karnataka -560073"},
                    {Name: "Dr. Jayapriya J", Role: "Department of Computer Science, Christ (Deemed to be University), Bangalore Yeshwantpur campus, Nagasandra, Bengaluru, Karnataka -560073"},
                    {Name: "Dr. Mahalakshmi J", Role: "Department of Computer Science, Christ (Deemed to be University), Bangalore Yeshwantpur campus, Nagasandra, Bengaluru, Karnataka -560073"},
                    {Name: "Dr. Kokilavani T", Role: "Department of Computer Science, Christ (Deemed to be University), Bangalore Yeshwantpur campus, Nagasandra, Bengaluru, Karnataka -560073"},
                    {Name: "Dr. Shikhar Tyagi", Role: "Department of Computer Science, Christ (Deemed to be University), Bangalore Yeshwantpur campus, Nagasandra, Bengaluru, Karnataka -560073"},
                    {Name: "Dr. V S Anita Sofia", Role: "Associate Professor, Department of Computer Applications (MCA), PSG College of Arts and Science"},
                    {Name: "Dr. J. Ramkumar", Role: "Sri Krishna Arts and Science College, Coimbatore"},
                    {Name: "Dr. S.Manju", Role: "Associate Professor, PSG College of Arts and Science"},
                    {Name: "Dr. Dr Jayadurga R", Role: "Department of Computer Science, Christ (Deemed to be University), Bangalore Yeshwantpur campus, Nagasandra, Bengaluru, Karnataka -560073"},
                    {Name: "Dr. Gayathry S Warrier", Role: "Department of Computer Science, Christ (Deemed to be University), Bangalore Yeshwantpur campus, Nagasandra, Bengaluru, Karnataka -560073"},
                    {Name: "Dr. Deepa S", Role: "Department of Computer Science, Christ (Deemed to be University), Bangalore Yeshwantpur campus, Nagasandra, Bengaluru, Karnataka -560073"},
                    {Name: "Dr. Saju Mathew", Role: "Shri Nehru Maha Vidyalaya College of Arts and Science, Ghambirmal Bafana Nagar, Malumachampatti, Coimbatore, Tamil Nadu, India"},
                    {Name: "Dr. Sridhar D", Role: "Dr. Vishwanath Karad MIT World Peace University, Pune, Maharashtra-411038, India"},
                    {Name: "Dr. N.Gnanasankaran", Role: "Department of Computer Science, Thiagarajar college, Madurai, 625009, Tamil Nadu, India"},
                    {Name: "Dr. JEHAN MURUGADHAS", Role: "IT Department, University of Technology and Applied Sciences-Nizwa"},
                    {Name: "Dr. K. Anandapadmanabhan", Role: "Dean, Sri Vasavi College (Self-Finance Wing), Erode"},
                    {Name: "Dr. Gouri M.S", Role: "Baselios MathewsII College of Engineering, Lake view, Muthupilakadu, Sasthamcotta, Kollam-690520"},
                    {Name: "Dr. D.FRANCIS XAVIER CHRISTOPHER", Role: "Principal of SRM TRICHY ARTS AND SCIENCE COLLEGE"},
                    {Name: "Dr. Kavita Gupta", Role: "University Institute of Computing, Chandigarh University, Gharuan"},
                    {Name: "Dr. G Lalitha", Role: "Measi Institute of Information Technology, Royapettah New college campus"},
                    {Name: "Dr. K SIVAKUMAR", Role: "Nehru Institute of Engineering and Technology, Coimbatore, Tamil Nadu"},
                    {Name: "Dr. Saranya", Role: "Department of computer science with data analytics"},
                    {Name: "Dr. Dileep V K", Role: "Assistant Professor, Department of CSE, LBSITW Poojapura, Thiruvananthapuram"},
                    {Name: "Dr. Dr.S.THILAGAVATHI", Role: "Sri Krishna Adithya College of Arts and Science, Kovaipudur, Coimbatore"},
                    {Name: "Dr. D. MENAKA", Role: "Dept of Electronics and Instrumentation Engineering, Noorul Islam Centre for Higher Education, Kumaracoil"},
                    {Name: "Dr. M.UMADEVI", Role: "SRI ADI CHUNCHANAGIRI WOMEN'S COLLEGE"},
                    {Name: "Dr. Jayan J. P.", Role: "Associate Professor & Head, Department of Software Engineering, Noorul Islam Centre for Higher Education, Kumaracoil"},
                    {Name: "Dr. V. JUDE NIRMAL", Role: "Department of Computer Science, St. Joseph's College (Autonomous), Tiruchirappalli - 620002, Tamil Nadu, India"},
                    {Name: "Dr. BEULAH S", Role: "Department of Computer Applications, NICHE"},
                    {Name: "Dr. Malathi A", Role: "PG and Research Department of Computer Science, Government Art College, Coimbatore"},
                    {Name: "Dr. M. Anita Indu", Role: "Department of Computer Applications, SSS Shasun Jain College, Chennai, Tamil Nadu"},
                    {Name: "Dr. A. SELVAKUMAR", Role: "Department of Computer Science, Sree Saraswathi Thyagaraja College, Pollachi"},
                    {Name: "Dr. K Padmavathi", Role: "Department of Computer Science, PSG College of Arts & Science, Coimbatore"},
                    {Name: "Dr. M SARAVANAMUTHU", Role: "MADANAPALLE INSTITUTE OF TECHNOLOGY AND SCIENCE"},
                    {Name: "Dr. PAnu", Role: "SCHOOL OF COMPUTING, Satra Deemed UNIVERSITY, Thanjavur"},
                    {Name: "Dr. P.Venkadesh", Role: "V.S.B College of Engineering Technical Campus, Coimbatore"},
                    {Name: "Dr. S.V.Divya", Role: "Department of CSE, V.S.B College of Engineering Technical Campus, Coimbatore"},
                    {Name: "Dr. M. SENTHILKUMAR", Role: "Department of Computer Science, Puratchi Thalaivi Amma Government Arts and Science College, Palladam 641664"},
                    {Name: "Dr. ANOOP SREEKUMAR R. S.", Role: "Department of Artificial intelligence/ CSE, Baselios Mathews II College of Engineering, Sasthamkotta, Kollam"},
                    {Name: "Dr. Juliet Rozario", Role: "Department of Computer Science, Nehru Arts and Science College"},
                    {Name: "Dr. JOTHIKUMAR R", Role: "Department of CSE, SHADAN COLLEGE OF ENGINEERING AND TECHNOLOGY, HYDERABAD"},
                    {Name: "Dr. Teena Jose", Role: "Department of Computer Science, Christ (Deemed to be University), Bangalore Yeshwantpur campus, Nagasandra, Bengaluru, Karnataka -560073"},
                    {Name: "Dr. P.Thangaraju", Role: "Dept of Computer Applications, Bishop Heber College, Tiruchirappalli"},
                    {Name: "Dr. Krishan Tuli", Role: "University Institute of Computing, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. Anand Muni Mishra", Role: "University Institute of Computing, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. Joe Arun Raja Ponnusamy", Role: "Department of MCA, University Institute of Computing"},
                    {Name: "Dr. C Thiyagarajan", Role: "PSG College of Arts & Science, Coimbatore 14"},
                    {Name: "Dr. RASADURAI", Role: "Kuppam Engineering College, Kuppam 517425"},
                    {Name: "Dr. Jameel Ahmad Qurashi", Role: "Associate Professor, Poornima University, Jaipur, Rajasthan"},
                    {Name: "Dr. Dr. Rohit Kumar", Role: "Govt College, Raipur Rani, Panchkula"},
                    {Name: "Dr. chenthalir indra", Role: "Computer Science Department, S. T. Hindu College, Nagercoil, Tamil Nadu, 629001"},
                    {Name: "Dr. M MOHAMMED MUSTAFA", Role: "Associate Professor · Sri Krishna College of Engineering and Technology"},
                    {Name: "Dr. Ashish Kumar", Role: "Assistant Professor, Chitkara University, Punjab"},
                    {Name: "Dr. P. Prema", Role: "Department of Computer Science, Government Arts and Science College, Kallakurichi"},
                    {Name: "Dr. R.Rajalakshmi", Role: "Dept of Computer Science (PG), Noorul Islam College of Arts & Science"},
                    {Name: "Dr. Sawroop kaur", Role: "University Institute of Computing, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. Kirti Walia", Role: "University Institute of Computing, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. Monika Kalra", Role: "University Institute of Computing, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. Vikas Sharma", Role: "University Institute of Computing, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. Monika", Role: "Department of Computer Applications, Panipat Institute of Engineering and Technology (PIET), Panipat, Haryana"},
                    {Name: "Dr. Gagandeep Kaur", Role: "University Institute of Computing, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. Nitin Jain", Role: "University Institute of Computing, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. SULPHIKAR A", Role: "LBS College of Engineering, Kasaragod, Kerala"},
                    {Name: "Dr. Sujit Kumar Singh", Role: "HOD, CA & B.Sc. Data Science, Asansol Engineering College, Mewar University, Asansol, West Bengal, India"},
                    {Name: "Dr. Nitin Pathak", Role: "USB-Commerce, Chandigarh University, Mohali"},
                    {Name: "Dr. Jasminder Kaur Sandhu", Role: "University Institute of Computing, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. K. Rajakumari", Role: "Bharath Institute of Higher Education and Research"},
                    {Name: "Dr. Kiran Malik", Role: "MRIEM-Matu Ram Institute of Engineering and Management"},
                    {Name: "Dr. S. MUTHUSELVAN", Role: "KCG College of Technology, Chennai"},
                    {Name: "Dr. SALIL BHARANY", Role: "Assistant Professor, Lovely Professional University"},
                    {Name: "Dr. Munish Gupta", Role: "Associate Professor, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. K.HAZEENA", Role: "MEASI Institute of Information Technology"},
                    {Name: "Dr. Karthick Panneerselvan", Role: "School of Computer Applications, Lovely Professional University"},
                    {Name: "Dr. P.Logeswari", Role: "Acharya Institute of Graduate Studies, Bangalore"},
                    {Name: "Dr. Shailendra Kumar Singh", Role: "Lovely Professional University, Jalandhar, Punjab"},
                    {Name: "Dr. salil arora", Role: "Guru Nanak Dev University, Amritsar, Punjab"},
                    {Name: "Dr. Deeksha Baweja", Role: "Assistant Professor, Chandigarh University"},
                    {Name: "Dr. Amairullah Khan Lodhi", Role: "Shadan College of Engineering and Technology, Hyderabad"},
                    {Name: "Dr. Senthil Kumar Janahan", Role: "Associate Professor, Lovely Professional University"},
                    {Name: "Dr. Malvinder singh Bali", Role: "CSE Department, Lovely Professional University"},
                    {Name: "Dr. Varsha sahni", Role: "Lovely Professional University"},
                    {Name: "Dr. Sumit Kushwaha", Role: "University Institute of Computing, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. Dr. R. Kavitha", Role: "AP-III, CSE, SASTRA University, Thanjavur"},
                    {Name: "Dr. Kala K U", Role: "School of CS and IT, Jain deemed to be University, Bangalore"},
                    {Name: "Dr. LUCIA AGNES BEENA", Role: "St. Joseph's College (Autonomous), Tiruchirappalli - 620002"},
                    {Name: "Dr. S.S.Sujatha", Role: "S.A.V Sahaya Thai College of Arts and Science, Vadakkankulam"},
                    {Name: "Dr. Deepthi P S", Role: "Dept of CSE, LBS Institute of Technology for Women, Poojappura"},
                    {Name: "Dr. Dr.S.S.Sujatha", Role: "Dept. of Computer Science, S.A.V Sahaya Thai Arts and Science College, Vadakkankulam"},
                    {Name: "Dr. Soni singh", Role: "Lovely Professional University, Phagwara, Punjab, India"},
                    {Name: "Dr. Harpreet Kaur", Role: "Lovely Professional University"},
                    {Name: "Dr. T.S.Shanthi", Role: "S.A.V. Sahaya Thai Arts and Science (Women) College"},
                    {Name: "Dr. S.Muthulakshmi", Role: "Mohamed Sathak College of Arts and Science"},
                    {Name: "Dr. Sagaya Aurelia", Role: "Department of Computer Science, Christ (Deemed to be University), Bangalore"},
                    {Name: "Dr. Ramandeep Sandhu", Role: "Assistant Professor, School of Computer Science Engineering, Lovely Professional University"},
                    {Name: "Dr. Anbarasi", Role: "Department of Computer Science, Government Arts and Science College for Women"},
                    {Name: "Dr. Kanwal Preet Kour", Role: "Assistant Professor, Lovely Professional University"},
                    {Name: "Dr. Yasir Iqbal Mir", Role: "Room no 502, Block 5, Knowledge park III, Sharda University, Greater Noida, UP"},
                    {Name: "Dr. Dr. Mohammed Abdul Bari", Role: "Department of Computer Science & Engineering, Keshav Memorial Engineering College"},
                    {Name: "Dr. S. Geetha", Role: "Government Arts and Science College for Women, Coimbatore"},
                    {Name: "Dr. M.NANDHINI", Role: "Government Arts and Science College for Women, Puliakulam, Coimbatore-45"},
                    {Name: "Dr. LENIN KUMAR", Role: "Vignan Institute of Technology and Science, Hyderabad"},
                    {Name: "Dr. A. Anitha", Role: "Department of Computer Science and Engineering, Noorul Islam Centre for Higher Education, Kanyakumari District"},
                    {Name: "Dr. S. SIVABALAN", Role: "School of Computing and Informatics, Vignan University, Guntur, Andhra Pradesh"},
                    {Name: "Dr. Stephen R", Role: "Department of Computer Science, Christ (Deemed to be University), Bangalore Yeshwantpur campus, Nagasandra, Bengaluru, Karnataka -560073"},
                    {Name: "Dr. Ankur Rai", Role: "Assistant Professor, Institute of Engineering & Technology, GLA University, Mathura"},
                    {Name: "Dr. VELMURUGAN V P", Role: "Faculty of Management Studies, Noorul Islam Centre for Higher Education, Kanyakumari 629180, Tamil Nadu, India"},
                    {Name: "Dr. K.Siva Sankar", Role: "Department of IT, Noorul Islam Centre for Higher Education"},
                    {Name: "Dr. PAZHANI KUMAR", Role: "Head, Department of Computer Science, S.T. Hindu College, Nagercoil"},
                    {Name: "Dr. R.Jayanthi", Role: "Department of Computer Science, Jain (Deemed-to-be-University), Bangalore"},
                    {Name: "Dr. G.Kalpana", Role: "Department of Computer Science, Sri Ramakrishna College of Arts & Science for Women"},
                    {Name: "Dr. Dr. Syed Mohtashim Mian", Role: "Assistant Professor, Computer Science, SRM University, Sonepat, Haryana"},
                    {Name: "Dr. Satyavathy Gunalan", Role: "Professor & Head, Department of Computer Science with Data Analytics, KPR College of Arts Science and Research, Coimbatore-641407"},
                    {Name: "Dr. T Thendral", Role: "Sri Ramakrishna College of Arts and Science for Women"},
                    {Name: "Dr. C.Rathika", Role: "Sri Ramakrishna College of Arts and Science for Women"},
                    {Name: "Dr. PRABHAKARAN M", Role: "Department of Computer Science, Jain (Deemed-to-be-University), Bangalore"},
                    {Name: "Dr. S.Preetha", Role: "Department of computer science, Sri Ramakrishna College of Arts and Science for women, Coimbatore"},
                    {Name: "Dr. D.Anitha", Role: "Sri Ramakrishna College of Arts and Science for Women, Coimbatore"},
                    {Name: "Dr. Vijayalakshmi.S", Role: "Sri Ramakrishna College of Arts and Science for Women, Coimbatore"},
                    {Name: "Dr. R.Khanchana", Role: "Assistant Professor, Department of Computer Science, Sri Ramakrishna College of Arts and Science for Women, Coimbatore"},
                    {Name: "Dr. P.Dhanalakshmi", Role: "Assistant Professor, Department of Computer Science, Sri Ramakrishna College of Arts and Science for Women, Coimbatore"},
                    {Name: "Dr. Sangeetha D", Role: "Department of Computer Science & Applications, MIT World Peace University"},
                    {Name: "Dr. Mugunthan S R", Role: "Department of Computer Science & Applications, MIT World Peace University"},
                    {Name: "Dr. Julia Punitha Malar Dhas", Role: "Karunya Institute of Technology and Sciences, Coimbatore-641114"},
                    {Name: "Dr. Meena Suguanthi.G", Role: "Karpagam Academy of Higher Education"},
                    {Name: "Dr. Dr.B.Vasumathi", Role: "Department of Computational Sciences, Brainware University, West Bengal, India"},
                    {Name: "Dr. Dr.D.Gayathri Devi", Role: "Sri Ramakrishna College of Arts and Science for Women"},
                    {Name: "Dr. Jemima Priyadarsini", Role: "Bishop Heber College, Trichy"},
                    {Name: "Dr. Mudassir Khan", Role: "King Khalid University, Saudi Arabia"},
                    {Name: "Vignesh K", Role: "Kumaraguru College of Technology, Coimbatore"},
                    {Name: "Dr. Kavitha V", Role: "Dept of Computer Science with Cognitive Systems, Sri Ramakrishna College of Arts and Science"},
                    {Name: "Dr. K. Asha", Role: "Faculty of Management Studies, Noorul Islam Centre for Higher Education"},
                    {Name: "Dr. Abhimanyu Singh Yadav", Role: "Department of Statistics, Banaras Hindu University Varanasi"},
                    {Name: "Dr. S ANNAL EZHIL SELVI", Role: "Bishop Heber College"},
                    {Name: "Dr. Neera Kumari", Role: "D. Y. Patil International University, Akurdi, Pune, Maharashtra"},
                    {Name: "Dr. V A JANE", Role: "Assistant Professor, Department of B.Voc (SD & SA), St. Joseph's College, Trichy"},
                    {Name: "Dr. Stephen A", Role: "Kristu Jayanti College, Bengaluru"},
                    {Name: "Dr. Yamini.C", Role: "Sri Ramakrishna College of Arts and Science for Women"},
                    {Name: "Dr. Sonia", Role: "Assistant Professor, Chandigarh University"},
                    {Name: "Dr. DR PRAVEEN KUMAR MISRA", Role: "Dept. of Mathematics and Statistics, Dr. Shakuntala Misra National Rehabilitation University, Lucknow"},
                    {Name: "Dr. H. M. LEENA", Role: "Holy Cross College (Autonomous), Tiruchirappalli, Tamilnadu"},
                    {Name: "Dr. Ashok Kumar", Role: "Department of Statistics, University of Lucknow, Lucknow"},
                    {Name: "Dr. Suresh K", Role: "Department of Computer Science, Christ (Deemed to be University), Bangalore"},
                    {Name: "Dr. Jenifer Jothi Mary A", Role: "Department of Computer Science, St Joseph's College (Autonomous), Tiruchirappalli-2"},
                    {Name: "Dr. S. Vaaheedha Kfatheen", Role: "Department of Computer Science, Jamal Mohamed College, Trichy - 620 020"},
                    {Name: "Dr. V Umarani", Role: "Dept of Computer Applications, PSG College of Technology, Coimbatore"},
                    {Name: "Dr. G. Arockia Sahaya sheela", Role: "Head, Department of Data Science, Holy Cross College, Trichy"},
                    {Name: "Dr. Vijay Arputharaj J", Role: "Department of Computer Science, Christ (Deemed to be University), Bangalore 560029"},
                    {Name: "Dr. Neelamegam Chandirakasan", Role: "Information Communication Technology Teacher, SGIS Institutions"},
                    {Name: "Dr. Vishwa Priya V", Role: "Vels Institute of Science, Technology and Advanced Studies, Chennai"},
                    {Name: "Dr. Tamilselvi. P", Role: "Vels Institute of Science, Technology and Advanced Studies, Chennai"},
                    {Name: "Dr. Senthil Vadivu M", Role: "Department of Statistics and Data Science, Christ University, Bengaluru Central Campus"},
                    {Name: "Dr. Jose Reena K", Role: "Vels Institute of Science, Technology and Advanced Studies, Chennai"},
                    {Name: "Dr. Flower Queen M P", Role: "SRM TRP Engineering College, Trichy"},
                    {Name: "Dr. Amit Garg", Role: "Associate Professor, CSE Department, Manipal University, Jaipur"},
                    {Name: "Dr. Sajitha A V", Role: "Mohandas College of Engineering And Technology, Anad, Kerala"},
                    {Name: "Dr. K R Martin", Role: "Dept of Computer Science, St. Joseph's College, Trichy 620002"},
                    {Name: "Dr. Prof. Manjaiah D H", Role: "Senior Professor & Chairman, Dept. of PG Studies and Research in Computer Science, Mangalore University, India"},
                    {Name: "Dr. Ravinder kaur", Role: "Assistant Professor, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. Robinson Joel M", Role: "Associate Professor, Department of Information Technology, Kings Engineering College, Chennai"},
                    {Name: "Dr. Christophe Chesneau", Role: "Campus 2, LMNO, Université de Caen-Normandie, 14000, Caen"},
                    {Name: "Dr. M S Safna Asiq", Role: "Arunachala Arts and Science (Women) College, Vellichanthai"},
                    {Name: "Dr. Mathu Soothana S Kumar", Role: "Associate Professor, Noorul Islam Centre for Higher Education, Tamil Nadu"},
                    {Name: "Dr. Krishna Kumar Mohbey", Role: "Central University of Rajasthan"},
                    {Name: "Dr. S Maria Celestin Vigila", Role: "Department of IT, Noorul Islam Centre for Higher Education, Kumaracoil"},
                    {Name: "Dr. Gurpreet Kaur", Role: "University Institute of Computing, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. M. JEYA SUTHA", Role: "Department of Computer Applications, St. Xavier's Catholic College of Engineering, Chunkankadai, Nagercoil"},
                    {Name: "Dr. Praveen Kumar", Role: "University Institute of Computing, Chandigarh University, Gharuan, Mohali, Punjab"},
                    {Name: "Dr. P. Ajitha", Role: "Department of Software Systems & Computer Science (PG), KG College of Arts and Science, Coimbatore, Tamilnadu"},
                    {Name: "Dr. Ben Sujitha B", Role: "Noorul Islam Centre for Higher Education"},
                    {Name: "Dr. V. Sulochana", Role: "Hindusthan College of Arts & Science"}
                ]               
        }
    
</script>